In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# df1 = pd.read_csv('suumo_tokyo0.csv', sep = '\t',encoding='utf-16', names= ['マンション名', '住所', '区', '市町村', '間取り', '間取りDK', '間取りK', '間取りL', '間取りS',
#        '築年数', '建物高さ', '階1', '専有面積', '賃料+管理費', '敷/礼/保証金', '路線1', '駅1',
#        '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', '賃料', '管理費', '敷金',
#        '礼金', '保証金', '敷引,償却'])
# df2 = pd.read_csv('suumo_tokyo2.csv', sep = '\t',encoding='utf-16', names= ['Unnamed: 0','マンション名', '住所', '区', '市町村', '間取り', '間取りDK', '間取りK', '間取りL', '間取りS',
#        '築年数', '建物高さ', '階1', '専有面積', '賃料+管理費', '敷/礼/保証金', '路線1', '駅1',
#        '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', '賃料', '管理費', '敷金',
#        '礼金', '保証金', '敷引,償却'])
# df3 = pd.read_csv('suumo_tokyo3.csv', sep = '\t',encoding='utf-16',  names= ['Unnamed: 0','マンション名', '住所', '区', '市町村', '間取り', '間取りDK', '間取りK', '間取りL', '間取りS',
#        '築年数', '建物高さ', '階1', '専有面積', '賃料+管理費', '敷/礼/保証金', '路線1', '駅1',
#        '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', '賃料', '管理費', '敷金',
#        '礼金', '保証金', '敷引,償却'])
df1 = pd.read_csv('suumo_tokyo0.csv', sep = '\t',encoding='utf-16')
df2 = pd.read_csv('suumo_tokyo2.csv', sep = '\t',encoding='utf-16')
df3 = pd.read_csv('suumo_tokyo3.csv', sep = '\t',encoding='utf-16')

In [3]:
df1['区']=df1['区'].str.split('川崎市').apply(lambda x: x[1])

In [4]:
df = df1.append([df2,df3])

In [30]:
df['バス1']=df['駅1'].str.split(' ').apply(lambda x: x[1].replace('バス','').replace('分','') if len(x) > 1 else  None)
df['バス2']=df['駅2'].str.split(' ').apply(lambda x: x[1].replace('バス','').replace('分','') if len(x) > 1 else  None)
df['バス3']=df['駅3'].str.split(' ').apply(lambda x: x[1].replace('バス','').replace('分','') if len(x) > 1 else  None)

In [31]:
df['駅1']=df['駅1'].str.split(' ').apply(lambda x: x[0])
df['駅2']=df['駅2'].str.split(' ').apply(lambda x: x[0])
df['駅3']=df['駅3'].str.split(' ').apply(lambda x: x[0])

In [32]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)
df.drop([0],axis=0,inplace=True)

In [33]:
df.tail()

マンション名          住所    区   市町村  間取り  間取りDK  間取りK  間取りL  \
4026  東急大井町線 荏原町駅 2階建 築58年  東京都品川区旗の台２  品川区  旗の台２    1      0     1     0   
4027                   田丸荘  東京都品川区旗の台２  品川区  旗の台２    1      0     1     0   
4028  ＪＲ京浜東北線 大森駅 3階建 築35年   東京都品川区大井７  品川区   大井７    1      0     1     0   
4029  ＪＲ京浜東北線 大森駅 3階建 築35年   東京都品川区大井７  品川区   大井７    1      0     1     0   
4030    ＪＲ山手線 品川駅 6階建 築54年  東京都品川区北品川１  品川区  北品川１    1      0     1     0   

      間取りS  築年数  ...   徒歩3       賃料   管理費       敷金       礼金  保証金 敷引,償却   バス1  \
4026     0   33  ...     7  50000.0  5000  50000.0  50000.0  0.0   0.0  None   
4027     0   33  ...    12  40000.0  3000  40000.0  40000.0  0.0   0.0  None   
4028     0   33  ...    19  70000.0  3000  70000.0  70000.0  0.0   0.0  None   
4029     0   33  ...    19  70000.0  3000  70000.0  70000.0  0.0   0.0  None   
4030     0   33  ...     8  65000.0     0  65000.0  65000.0  0.0   0.0  None   

       バス2   バス3  
4026  None  None  
4027  None  None  
4028  None  None  
4029  None  None  
4030  None  None  

[5 rows x 33 columns]

In [76]:
df.columns.values

array(['マンション名', '住所', '区', '市町村', '間取り', '間取りDK', '間取りK', '間取りL', '間取りS',
       '築年数', '建物高さ', '階1', '専有面積', '賃料+管理費', '敷/礼/保証金', '路線1', '駅1',
       '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', '賃料', '管理費', '敷金',
       '礼金', '保証金', '敷引,償却'], dtype=object)

In [7]:
df['路線1'].head()

1     ＪＲ横須賀線
2     ＪＲ横須賀線
3    ＪＲ京浜東北線
4      東急東横線
5      東急東横線
Name: 路線1, dtype: object

In [144]:
df['区'].head()

1    6
2    6
3    5
4    2
5    2
Name: 区, dtype: int64

In [34]:
 names= ['マンション名', '住所', '区', '市町村', '間取り', '間取りDK', '間取りK', '間取りL', '間取りS',
       '築年数', '建物高さ', '階1', '専有面積', '賃料+管理費', '敷/礼/保証金', '路線1', '駅1',
       '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', '賃料', '管理費', '敷金',
       '礼金', '保証金', '敷引,償却','バス1','バス2','バス3']
categorial_features = ['区', '間取りDK', '間取りK', '間取りL', '間取りS',
       '路線1', '駅1', '路線2', '駅2', '路線3', '駅3']

In [35]:
dropp = ['マンション名', '住所', '間取り','敷金','賃料', '管理費','賃料+管理費','市町村','敷金','敷/礼/保証金',
       '礼金', '保証金', '敷引,償却']

In [36]:
tfvocab = [ 
       '築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3', 'バス1','バス2','バス3',
'区', '間取りDK', '間取りK', '間取りL', '間取りS',
       '路線1', '駅1', '路線2', '駅2', '路線3', '駅3'
]

In [37]:
from sklearn import preprocessing

In [38]:
lbl = preprocessing.LabelEncoder()
for col in categorial_features:
    df[col] = lbl.fit_transform(df[col].astype(str))

In [39]:
# for col in tfvocab:
#     df[col] = lbl.fit_transform(df[col].astype(float))
df[['築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3','バス1','バス2','バス3']] = df[['築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3','バス1','バス2','バス3']].apply(pd.to_numeric)

In [40]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split

In [41]:
y = df['賃料+管理費'].apply(pd.to_numeric)
X = df.drop(dropp,axis=1)

In [34]:
# lbl.fit_transform(y.astype(float))

array([140, 140, 133, ..., 146, 146, 111])

In [42]:
X_train, X_valid, y_train, y_valid = train_test_split(X,y,test_size=0.2) 

In [61]:
lgb_param = {
    'task': 'train',
    'boosting_type' : 'gbdt',
    'objective': 'regression',
    'num_boost_round':30000,
    'early_stopping':200,
    'num_leaves': 80,
     'max_depth': 7,
#     'num_class': 8,
    'metric': 'rmse',
#     'max_depth': 20,
#     'num_leaves': 37,
    'feature_fraction': 0.7,
    'bagging_fraction': 0.8,
    'learning_rate':0.001,
    'verbosity': 200    
#     'min_data': 1,
#     'min_data_in_bin': 1
}

In [62]:
lgtrain = lgb.Dataset(X_train,y_train,feature_name=tfvocab, categorical_feature= categorial_features)
lgvalid = lgb.Dataset(X_valid,y_valid,feature_name=tfvocab, categorical_feature= categorial_features)

In [63]:
lgb_clf = lgb.train(lgb_param,lgtrain, valid_sets=[lgtrain,lgvalid], valid_names=['train','valid'])

/usr/local/lib/python3.6/site-packages/lightgbm/engine.py:99: UserWarning: Found `num_boost_round` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/usr/local/lib/python3.6/site-packages/lightgbm/engine.py:104: UserWarning: Found `early_stopping` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/usr/local/lib/python3.6/site-packages/lightgbm/basic.py:1036: UserWarning: Using categorical_feature in Dataset.
  warnings.warn('Using categorical_feature in Dataset.')
/usr/local/lib/python3.6/site-packages/lightgbm/basic.py:681: UserWarning: categorical_feature in param dict is overrided.
  warnings.warn('categorical_feature in param dict is overrided.')


[1]	train's rmse: 31225.8	valid's rmse: 30025.1
Training until validation scores don't improve for 200 rounds.
[2]	train's rmse: 31204.1	valid's rmse: 30004.9
[3]	train's rmse: 31182.3	valid's rmse: 29984.6
[4]	train's rmse: 31160.7	valid's rmse: 29964
[5]	train's rmse: 31138.9	valid's rmse: 29943.6
[6]	train's rmse: 31117.3	valid's rmse: 29923.2
[7]	train's rmse: 31102.9	valid's rmse: 29910.6
[8]	train's rmse: 31081.2	valid's rmse: 29890.2
[9]	train's rmse: 31059.4	valid's rmse: 29869.7
[10]	train's rmse: 31037.8	valid's rmse: 29849.8
[11]	train's rmse: 31018.9	valid's rmse: 29832.9
[12]	train's rmse: 30997.9	valid's rmse: 29812.9
[13]	train's rmse: 30978.6	valid's rmse: 29795.8
[14]	train's rmse: 30957.7	valid's rmse: 29776.1
[15]	train's rmse: 30938.6	valid's rmse: 29759.1
[16]	train's rmse: 30917.2	valid's rmse: 29739.3
[17]	train's rmse: 30898.1	valid's rmse: 29722.3
[18]	train's rmse: 30880.2	valid's rmse: 29706.5
[19]	train's rmse: 30859.3	valid's rmse: 29686.6
[20]	train's rmse

In [59]:
lgb_clf.predict(X_valid)

array([ 83810.66243679,  80885.04055793,  69719.82283567, ...,
        46486.2707392 ,  65907.73527463,  98050.19589794])

In [ ]:
lgb

In [64]:
import pickle
with open('model3.p','wb') as hand:
    pickle.dump(lgb_clf,hand,protocol=pickle.HIGHEST_PROTOCOL)

In [52]:
X_valid.columns

Index(['区', '間取りDK', '間取りK', '間取りL', '間取りS', '築年数', '建物高さ', '階1', '専有面積',
       '路線1', '駅1', '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3'],
      dtype='object')

In [65]:
with open('encoder3.p','wb') as hand:
    pickle.dump(lbl,hand,protocol=pickle.HIGHEST_PROTOCOL)

In [100]:
X_valid.head()

区  間取りDK  間取りK  間取りL  間取りS  築年数  建物高さ  階1   専有面積  路線1   駅1  徒歩1  路線2  \
4080  3      0     1     0     0   31     3   1  17.52    7   95    6   28   
9923  3      0     1     0     0    1     2   1  19.60    7   92   11   10   
2992  0      0     0     0     0    9     2   2  22.00   17  114    9   17   
8492  4      0     1     0     0    0    10   2  26.08   16   47    6   20   
4949  6      0     1     0     0   20     6   2  26.90   26   65   20   32   

      駅2  徒歩2  路線3   駅3  徒歩3  
4080  53   11   12   35   14  
9923  30   29   12  146   29  
2992  75   11   25  137   11  
8492  52   10   26  165   20  
4949  60    2   37  123    2

In [56]:
X_fake = X_valid.iloc[0,:].values

In [58]:
lgb_clf.predict([X_fake])

array([ 83810.66243679])

In [99]:
df[df['専有面積']==17.52]

マンション名              住所  区   市町村 間取り  間取りDK  間取りK  間取りL  \
1782         シティハイム　ラ・ポレール   神奈川県川崎市麻生区高石２  8   高石２   1      0     1     0   
1867         シティハイム　ＹＡＳＵＮＯ   神奈川県川崎市幸区古市場１  6  古市場１   1      0     1     0   
3633   ＪＲ南武線 宿河原駅 2階建 築29年  神奈川県川崎市多摩区宿河原４  3  宿河原４   1      0     1     0   
3634   ＪＲ南武線 宿河原駅 2階建 築29年  神奈川県川崎市多摩区宿河原４  3  宿河原４   1      0     1     0   
4013         シティハイム　ハウスオブＵ  神奈川県川崎市多摩区宿河原４  3  宿河原４   1      0     1     0   
4014         シティハイム　ハウスオブＵ  神奈川県川崎市多摩区宿河原４  3  宿河原４   1      0     1     0   
4080     小田急線 登戸駅 2階建 築27年    神奈川県川崎市多摩区登戸  3    登戸   1      0     1     0   
1144              シティハイム渡辺       東京都品川区小山５  0   小山５   1      0     1     0   
4010  ＪＲ京浜東北線 大森駅 3階建 築29年      東京都品川区西大井２  0  西大井２   1      0     1     0   

      間取りS  築年数  ...    徒歩2  路線3   駅3 徒歩3       賃料   管理費       敷金       礼金  \
1782     0   34  ...     13   12   81  23  28000.0  3000  28000.0      0.0   
1867     0   32  ...     22   36   68  43  44000.0  3000  44000.0      0.0   
3633     0   10  ...     17   12   37  30  34000.0  3000  34000.0      0.0   
3634     0   10  ...     17   12   37  30  35000.0  3000  35000.0      0.0   
4013     0   29  ...     17   12   37  30  34000.0  3000  34000.0      0.0   
4014     0   29  ...     17   12   37  30  35000.0  3000  35000.0      0.0   
4080     0   31  ...     11   12   35  14  46000.0  3000  46000.0      0.0   
1144     0   24  ...      8   25  137  15  57000.0  2000  57000.0      0.0   
4010     0   37  ...      7   23    7  19  63000.0     0  63000.0  63000.0   

      保証金  敷引,償却  
1782  0.0    0.0  
1867  0.0    0.0  
3633  0.0    0.0  
3634  0.0    0.0  
4013  0.0    0.0  
4014  0.0    0.0  
4080  0.0    0.0  
1144  0.0    0.0  
4010  0.0    0.0  

[9 rows x 30 columns]

In [78]:
df[['築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3']] = df[['築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3']].apply(pd.to_numeric)


In [69]:
X_valid.columns

Index(['区', '間取りDK', '間取りK', '間取りL', '間取りS', '築年数', '建物高さ', '階1', '専有面積',
       '路線1', '駅1', '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', 'バス1',
       'バス2', 'バス3'],
      dtype='object')

In [89]:
ans =['中原区',
 0,
 0,
 0,
 0,
 '30',
 '3',
 '1',
 '16.2',
 'ＪＲ横須賀線',
 '武蔵小杉駅',
 '6',
 '東急東横線',
 '武蔵小杉駅',
 '13',
 'ＪＲ南武線',
 '向河原駅',
 '3',
 0,
 0,
 0]

In [90]:
dfn = pd.DataFrame([ans],columns=['区', '間取りDK', '間取りK', '間取りL', '間取りS', '築年数', '建物高さ', '階1', '専有面積',
       '路線1', '駅1', '徒歩1', '路線2', '駅2', '徒歩2', '路線3', '駅3', '徒歩3', 'バス1',
       'バス2', 'バス3'])

In [91]:
dfn[['築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3','バス1','バス2','バス3']] = dfn[['築年数', '建物高さ', '階1', '専有面積',
       '徒歩1', '徒歩2', '徒歩3','バス1','バス2','バス3']].apply(pd.to_numeric)

In [92]:
for col in categorial_features:
    dfn[col] = lbl.fit_transform(dfn[col].astype(str))

In [93]:
dfn

区  間取りDK  間取りK  間取りL  間取りS  築年数  建物高さ  階1  専有面積  路線1 ...   徒歩1  路線2  駅2  \
0  0      0     0     0     0   30     3   1  16.2    0 ...     6    0   0   

   徒歩2  路線3  駅3  徒歩3  バス1  バス2  バス3  
0   13    0   0    3    0    0    0  

[1 rows x 21 columns]

In [94]:
lgb_clf.predict(dfn)

array([ 46809.81006239])